### ISSUE TITLE
tfField.getPhoneNumber() returning nil

### ISSUE THREAD

**Issue by jiffy-arti** [chronotruck/CTKFlagPhoneNumber#12]
I have my TextField in Storyboard. I changed the class name CTKFlagPhoneNumberTextField and module as CTKFlagPhoneNumber. Now while validating the number getPhoneNumber() is returning me nil but when I am printing text I can see the country code and number I entered. Is there any property I need to set. Need help. Thanks in advance.

**Comment by grifas** [comment]
Hi @jiffy-arti,

Thanks to report this issue. I'm investigating.

**Comment by grifas** [comment]
Do you tap on the done button to validate the number ?

**Comment by grifas** [comment]
@jiffy-arti Do you tap on the done button to validate the number ?

**Comment by jiffy-arti** [comment]
I am using "done" button as you given in the demo project. I have a submit button where I am checking my phone number's validation.

**Comment by grifas** [comment]
@jiffy-arti Which pod version have you ? The last pod version is `0.4.2`

**Comment by jiffy-arti** [comment]
Yes a I am using Swift4 and latest pod version which is 0.4.2.

**Comment by grifas** [comment]
Weird, I setted the textfield in storyboard like you and I have no problem.

Here my code:  

```
class ViewController: UIViewController {
	
	@IBOutlet weak var phoneNumberTextField: CTKFlagPhoneNumberTextField!
	
	override func viewDidLoad() {
		super.viewDidLoad()
		
		phoneNumberTextField.parentViewController = self

		let button = UIButton(type: .system)
		
		button.frame = CGRect(x: 0, y: 0, width: 50, height: 44)
		button.center = CGPoint(x: view.center.x, y: view.center.y + 60)
		button.setTitle("Ok", for: .normal)
		button.addTarget(self, action: #selector(validate), for: .touchUpInside)

		view.addSubview(button)
	}
	
	@objc func validate() {
		let phoneNumber: String? = phoneNumberTextField.getPhoneNumber()
		
		print(phoneNumber ?? "No phone number")
	}
}

```

When I type the last digit of the phone number and tap on OK button that print the phone number in the console.

**Comment by jiffy-arti** [comment]
In my version I cannot set parentViewController property. Its not declared in the swift file. I did check it twice.

**Comment by grifas** [comment]
`parentViewController ` has nothing to do with your issue. It's just for the country search.

Maybe you have not linked your textfield in the class with the textfield in your storyboard ?

**Comment by jiffy-arti** [comment]
![screen shot 2018-01-29 at 3 33 51 pm](https://user-images.githubusercontent.com/33309350/35504774-f90d19c4-0509-11e8-8a46-dcf05cd9b424.png)

There is no issue with the connection.

**Comment by grifas** [comment]
and in `Connections Inspector` tab ? The textfield has to be also linked here.

<img width="259" alt="screen shot 2018-01-29 at 11 06 23" src="https://user-images.githubusercontent.com/9267969/35504962-d6751e40-04e4-11e8-8630-135669df6662.png">

**Comment by jiffy-arti** [comment]
![screen shot 2018-01-29 at 3 43 35 pm](https://user-images.githubusercontent.com/33309350/35505153-36f56e98-050b-11e8-9052-cf59b34cab8c.png)

Connected.

**Comment by grifas** [comment]
Ok thank you. Can you provide me an exemple of the phone number that you're using to test ?

**Comment by grifas** [comment]
This one works in my code. 

You told me `In my version I cannot set parentViewController property. Its not declared in the swift file.` but you should find it (in 0.4.2) and be able to set it.

So are you sure you have the last pod version `0.4.2` ?

**Comment by jiffy-arti** [comment]
Thanks my installed version was 0.2.0 not 0.4.2. Thanks a lot no such issue in this version. Thanks a lot.
