### ISSUE TITLE
Country Code and Raw Number 

### ISSUE THREAD

**Issue by maniarali** [chronotruck/CTKFlagPhoneNumber#14]
Currently we are only able to get complete number through:
`print(phoneNumberTextField.getPhoneNumber())`

> // Output: +33600000001

Sometime country code and raw phone number is required rather than complete number, There must be 2 more methods.

`print(phoneNumberTextField.getCountryCode())` 

> // Output: +33

`print(phoneNumberTextField.getRawPhoneNumber())`

> 600000001

**Comment by grifas** [comment]
@maniarali Thanks to use this lib :) A new version is available (0.4.5) with those methods ;)
