### ISSUE TITLE
inputAccessoryView is setted to nil when you switch between flag picker and textField

### ISSUE THREAD

**Issue by alemohamad** [chronotruck/CTKFlagPhoneNumber#16]
When I touch the flag, the flag picker appears and it has an accessory view with a "Done" button. But when I touch the textField, the keypad doesn't have an accessory view. And I can't also add a custom accessory view made by me.

**Comment by grifas** [comment]
Thank you @alemohamad to use this library :)

I pushed a new pod version `0.4.6` that fixes this bug. The doc is in the README. Enjoy !
