### ISSUE TITLE
Library not support some functions

### ISSUE THREAD

**Issue by iVoGia** [chronotruck/CTKFlagPhoneNumber#17]
I am using this framework,
But, it's not support some methods.
print(phoneNumberTextField.getFormattedPhoneNumber())
print(phoneNumberTextField.getCountryPhoneCode())
print(phoneNumberTextField.getRawPhoneNumber()) 
I also cannot insert the search button like you.
How to fix it?
Please help me!

Thanks and Regard.

**Comment by grifas** [comment]
@iVoGia Thanks to use the lib :)

I think you have to update the pod with the `pod update` command line.

**Comment by iVoGia** [comment]
Yes, I will try.
I am update my pod file.
I hope it will work fine.

**Comment by iVoGia** [comment]
It work well !
Thanks.
But, I had a question .
How to display tableview same you .
Because, picker view, I cannot search the country, scroll is so long.

**Comment by grifas** [comment]
@iVoGia Please read the `Customization` section in the README.
