### ISSUE TITLE
Ability to disable flag button 

### ISSUE THREAD

**Issue by akilanarasu1994** [chronotruck/CTKFlagPhoneNumber#19]
Hi @grifas ! Love this project! 
In my current app, I'd like to freeze the flag to the US one. 
I took a look at the code ([PhoneNumberTextField.swift](https://github.com/chronotruck/CTKFlagPhoneNumber/blob/master/CTKFlagPhoneNumber/CTKFlagPhoneNumberTextField.swift)) and figured out that the flag button's user interaction needs to be disabled for this task. 

So basically, I'll have to change 
```swift 
private var flagButton: UIButton!
``` 
to 
```swift
public var flagButton: UIButton!
```
**or**
create a method to update the button's characteristics.

Which approach do you recommend, and is it alright if I submit a PR with this enhancement?

**Comment by grifas** [comment]
Hi @akilanarasu1994 thanks to use this lib :)

I think to pass the flagButton to public like this people can customize it as they want. It will be a part of improvements in the coming days.

**Comment by akilanarasu1994** [comment]
Hi @grifas , I've already made this customization. Since I didn't want to disturb the project, I created a private pod. The changes work perfectly!

I'll make the changes in my fork and create a PR. Is that alright?

**Comment by grifas** [comment]
Yes it is ;)
