### ISSUE TITLE
Bug for Nederlands (+31) and may be for some others countries

### ISSUE THREAD

**Issue by krunduev** [chronotruck/CTKFlagPhoneNumber#24]
For Netherlands (+31) the functions getFormattedPhoneNumber() and getRawPhoneNumber() return nil

**Comment by grifas** [comment]
Hi @krunduev, is it a valid phone number ? I invite you to try your phone number on https://numverify.com. Keep me in touch :)

**Comment by krunduev** [comment]
Our user affirm that the number is valid but https://numverify.com gives "Invalid Format" error.
This number is like to +319700177xxxx (last four digits modified). Look likes it's not your bug.
Thank you a lot!!!

**Comment by grifas** [comment]
@krunduev Can you also test your phone number on https://libphonenumber.appspot.com and copy here the result ?

**Comment by krunduev** [comment]
The same. Sorry

Validation Results
--
false
TOO_LONG
Note: numbers that are not possible have type UNKNOWN, an unknown region, and are considered invalid.
