### ISSUE TITLE
Flags not showing

### ISSUE THREAD

**Issue by gabrielcandiag** [chronotruck/CTKFlagPhoneNumber#26]
I was using the library and suddenly when I change the view controller to another part of the app, the flags are not visible now.

I tried with the default textfield without much configuration and is still not working.

<img width="511" alt="screen shot 2018-06-19 at 4 46 31 pm" src="https://user-images.githubusercontent.com/10672431/41623362-7fd905ea-73e0-11e8-97c9-65ff8bd56720.png">

**Comment by gabrielcandiag** [comment]
I'm adding the textfield to a Viewcontroller and presenting that view. In the viewDidLoad I'm doing this configuration:
`@IBOutlet weak var phoneTextField: CTKFlagPhoneNumberTextField!`

`self.phoneTextField.setFlag(with: "CL")`
`self.phoneTextField.parentViewController = self`
`self.phoneTextField.addTarget(self, action: #selector(textFieldDidChange(_:)), for: .editingChanged)`
`self.phoneTextField.font = UIFont.semiBold(size: 16)`
`self.phoneTextField.textColor = UIColor.slateGray`

It works when I present the ViewController from the LaunchView, but it doesn't work when I'm presenting the view from the mainView of the app. Both times is being presented in the same way without navigation controller.

**Comment by grifas** [comment]
@gabrielcandiag may be by removing your derived data and cleaning your project can resolve this. Otherwise I invite you to provide me a GitHub repository with a fresh project where occurs this issue.

**Comment by grifas** [comment]
I close this issue because there is no more activity on it.

**Comment by vozamlA** [comment]
Flags dont show

**Comment by AdieOlami** [comment]
This is still an issue
