### ISSUE TITLE
CTKFlagPhoneNumberTextField's  init?(coder aDecoder: NSCoder) not implemented.

### ISSUE THREAD

**Issue by fvolchyok** [chronotruck/CTKFlagPhoneNumber#3]
Is there any reason to not do something like this:? 

        required public init?(coder aDecoder: NSCoder) {
                super.init(coder: aDecoder)
                setup()
        }

Right now due to current implementation it is impossible to create CTKFlagPhoneNumberTextField in .xib file or storyboard. If there are no reasons to disallow creation from xibs it would be awesome to implement initWithCoder.

**Comment by grifas** [comment]
Hi,

Thanks you for your suggestion. I will add `initWithCoder` today ;)

**Comment by fvolchyok** [comment]
@grifas Thanks, it would help a lot!

**Comment by grifas** [comment]
It's done !
