### ISSUE TITLE
Issue while setting phone number using phoneNumberTextField.set

### ISSUE THREAD

**Issue by GirirajMulay** [chronotruck/CTKFlagPhoneNumber#30]
While we set number to CTKFlagPhoneNumberTextField it was reflecting with proper country flag 

After your last committed changes number is not getting set to textfield.

I have installed pods, changed Class of UITextfield to CTKFlagPhoneNumberTextField
and just used your given method 
phoneNumberTextField.set(phoneNumber: "some number with country code")

This was working fine before your last commit, now I am facing problems

what happens is textfield gets set to empty and and when I try to set it manually I am not able to see flags of desired countries?

This issue I was facing on pod version (0.4.6)

**Comment by grifas** [comment]
Hi @GirirajMulay Which last commit do you speak about ? The last version is `0.5.0`, have you try it ?

**Comment by GirirajMulay** [comment]
After your commit on July 13, 2018 it is not working 
I have tried previous code that is July 2,2018

Could you please let me know the pod version of July 2,2018 's commit

**Comment by grifas** [comment]
The commit on July 13 2018 doesn't change any code so I don't understand how it can be not working.

The pod version of July 2 2018 is `0.5.0`.

**Comment by GirirajMulay** [comment]
I am integrating your pod with objective c code, while installing pod following  versions are getting installed.. 
Downloading dependencies
Using CTKFlagPhoneNumber (0.4.6)
Using libPhoneNumber-iOS (0.9.13)

I have also tried installing version you mentioned i.e  0.5.0, 
 use_frameworks!
 pod 'CTKFlagPhoneNumber' '~> 0.5.0'

but it fails giving this error
Analyzing dependencies
[!] Unable to find a specification for `CTKFlagPhoneNumber~> 0.5.0`

**Comment by grifas** [comment]
Retry with a coma: `pod 'CTKFlagPhoneNumber', '~> 0.5.0'`  but just `pod 'CTKFlagPhoneNumber'` should be work with `pod install`/`pod update`.

**Comment by GirirajMulay** [comment]
**yes I know its not working still pod 'CTKFlagPhoneNumber', '~> 0.5.0'** 
it gives following error

[!] CocoaPods could not find compatible versions for pod "CTKFlagPhoneNumber":
  In Podfile:
    CTKFlagPhoneNumber (~> 0.5.0)

None of your spec sources contain a spec satisfying the dependency: `CTKFlagPhoneNumber (~> 0.5.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**also tried pod update, its not getting updated gives this error**  

[!] Failed to connect to GitHub to update the CocoaPods/Specs specs repo - Please check if you are offline, or that GitHub is down

**Comment by grifas** [comment]
Have you try `pod install --repo-update` ? Or may be `pod deintegrate` to remove pod then `pod intall` ?

I have no problem to install `0.5.0` in a new project.

**Comment by GirirajMulay** [comment]
I have tried deintegrating  pod file and installing new, but still it install 
same old version :
Using CTKFlagPhoneNumber (0.4.6)
Using libPhoneNumber-iOS (0.9.13)

**Comment by grifas** [comment]
Try to create a new project, install pod, install CTKFlagPhoneNumber. If there is no problem, the issue comes from your project. Otherwise, provide me the repo of this new project and I will investigate. Thank you

**Comment by GirirajMulay** [comment]
Yes could you please look into it, should I share link of my demo project here ?

**Comment by grifas** [comment]
I found it ;) I'll keep you in touch

**Comment by grifas** [comment]
I changed in your Podfile:
`pod 'CTKFlagPhoneNumber','~> 0.5.0'`
by
`pod 'CTKFlagPhoneNumber'`

 then `pod update` and the `0.5.0` is correctly installed.

**Comment by GirirajMulay** [comment]
I tried it : It gives me following error  :
pod update
Update all pods
Updating local specs repositories

[!] Failed to connect to GitHub to update the CocoaPods/Specs specs repo - Please check if you are offline, or that GitHub is down

My Cocoa pod version is 
 pod --version
1.5.3

**Comment by grifas** [comment]
I think it's not an issue from CTKFlagPhoneNumber pod. Check this  https://github.com/CocoaPods/CocoaPods/issues/7447.

**Comment by GirirajMulay** [comment]
ok I tried its getting updated may be its problem with my cocoa pods.
But even after updating pod file I am not able to import files and use it, have you used it what you have imported?

**Comment by grifas** [comment]
what do you mean by what did I import ? If you refer to importing the `CTKFlagPhoneNumber` repo directly into your project, it is also possible. But be sure to install its dependencies (`libPhoneNumber-iOS`).

I close this problem because it does not appear, apparently, from CTKFlagPhoneNumber.
