### ISSUE TITLE
Not able to set CTKFlagPhoneNumberTextField in storyBoard

### ISSUE THREAD

**Issue by hemaks777** [chronotruck/CTKFlagPhoneNumber#32]
### Expected behavior
I want to create CTKFlagPhoneNumberFields in storyboard itself.
### Actual behavior
Now its throwing error while setting textfield in storyBoard.
### Steps to reproduce the problem.
  1. Create an outlet of CTKFlagPhoneNumbertextField
  2. Set the initial setUp Codes.
### Specifications

**Comment by grifas** [comment]
Please fill all section in the template. Which pod version are you using ?

**Comment by hemaks777** [comment]
Hi,
Pod version is 1.5.3

**Comment by grifas** [comment]
Sorry, I mean which pod version **OF** CTKFlagPhoneNumber are you using ?

**Comment by hemaks777** [comment]
Hi,

CTKFlagPhoneNumber (0.4.7)

**Comment by grifas** [comment]
Please update it to `0.5.0`.

**Comment by hemaks777** [comment]
Hi,

Thank you for the solution,the issue has been solved. What are the changes in latest updated version?

**Comment by grifas** [comment]
The handling of the placeholder has been implemented in `0.5.0`. Thanks to use this lib ;)
