### ISSUE TITLE
stop editing countryTextField

### ISSUE THREAD

**Issue by PassantAbdelatif** [chronotruck/CTKFlagPhoneNumber#34]
when touch country text field at any place i expected to got countrypicker opened directly ,but i found that text field can be editing and i want to stop text field editing and make action not on flag only on text and flag image

**Comment by forTJ555** [comment]
facing same issue, i faced this when use it in scroll view. its working perfect in view but get issue while using in scroll view. it always show country picker even when not click on flag

**Comment by grifas** [comment]
It's because the scrollView's delays content touch is active. You can uncheck it on storyboard in Attribute Inspector or programmatically `UIScrollView().delaysContentTouches = false`.
