### ISSUE TITLE
get the country name

### ISSUE THREAD

**Issue by PadharO** [chronotruck/CTKFlagPhoneNumber#35]
HI,
thanks for the awesome library. Just wanted to know if there is any way to get the name of the country.
For eg. if I want to get the country code, I will select the particular country from the list. But if I want the country name of the selected country code , how can I get it?

Thanks in advcance

**Comment by grifas** [comment]
Hi thanks to use it ;) 

I think in the next release it will be possible to get the country object or a tuple of country code/name .

**Comment by grifas** [comment]
Please refer to this issue #33 to try to solve yours.
