### ISSUE TITLE
Flag is no updated after changing phone with set(phoneNumber: String)

### ISSUE THREAD

**Issue by fvolchyok** [chronotruck/CTKFlagPhoneNumber#4]
By default I have American flag set, but when I change phone to my Belarussian phone with `set(phoneNumber: String)`, flag doesn't changes (though phone changes properly and code accepted fine):

![image](https://user-images.githubusercontent.com/21335147/30706554-58f6514e-9f01-11e7-93b1-a00ae6f4548f.png)

Fortunately, it is easy to fix - seems like all one need to do is to add `setFlag(with: phoneUtil.getRegionCode(for: parsedPhoneNumber))` to CTKFlagPhoneNumberTextField.swift around 142 line. If required, I can make a fork and submit possible fixes via pull requests.

**Comment by grifas** [comment]
So I'm waiting your pull requests :)
