### ISSUE TITLE
Crash: _T018CTKFlagPhoneNumber15MRCountryPickerC15setCountryByRowySi3row_tF

### ISSUE THREAD

**Issue by osama-taha** [chronotruck/CTKFlagPhoneNumber#8]
Please take a look:

# OS version: 9.0.0
# Logs:
Crashed: com.apple.main-thread
0  CTKFlagPhoneNumber             0x100b34b64 _T018CTKFlagPhoneNumber15MRCountryPickerC15setCountryByRowySi3row_tF + 948
1  CTKFlagPhoneNumber             0x100b314fc _T018CTKFlagPhoneNumber0abC9TextFieldC5setup33_D5149F41D855A9C52E54B091304B013ELLyyF + 1148
2  CTKFlagPhoneNumber             0x100b32d4c _T018CTKFlagPhoneNumber0abC9TextFieldCACSgSo7NSCoderC5coder_tcfcTf4gn_n + 248
3  CTKFlagPhoneNumber             0x100b30fb0 _T018CTKFlagPhoneNumber0abC9TextFieldCACSgSo7NSCoderC5coder_tcfcTo + 36
4  UIKit                          0x18962ecb8 -[UIClassSwapper initWithCoder:] + 248
5  UIKit                          0x189743bf0 UINibDecoderDecodeObjectForValue + 672
6  UIKit                          0x189743d68 UINibDecoderDecodeObjectForValue + 1048
7  UIKit                          0x189743938 -[UINibDecoder decodeObjectForKey:] + 336
8  UIKit                          0x18947bfb4 -[UIView initWithCoder:] + 608
9  UIKit                          0x189743bf0 UINibDecoderDecodeObjectForValue + 672
10 UIKit                          0x189743938 -[UINibDecoder decodeObjectForKey:] + 336
11 UIKit                          0x18962e95c -[UIRuntimeConnection initWithCoder:] + 188
12 UIKit                          0x189743bf0 UINibDecoderDecodeObjectForValue + 672
13 UIKit                          0x189743d68 UINibDecoderDecodeObjectForValue + 1048
14 UIKit                          0x189743938 -[UINibDecoder decodeObjectForKey:] + 336
15 UIKit                          0x18962dc90 -[UINib instantiateWithOwner:options:] + 1220
16 UIKit                          0x1894e6cfc -[UIViewController _loadViewFromNibNamed:bundle:] + 376
17 UIKit                          0x1892bbea8 -[UIViewController loadView] + 176
18 UIKit                          0x189183258 -[UIViewController loadViewIfRequired] + 144
19 UIKit                          0x1891831b0 -[UIViewController view] + 28
20 UIKit                          0x1894f5c18 -[UIViewController _setPresentationController:] + 108
21 UIKit                          0x1894eee74 -[UIViewController _presentViewController:modalSourceViewController:presentationController:animationController:interactionController:completion:] + 1328
22 UIKit                          0x1894f085c -[UIViewController _presentViewController:withAnimationController:completion:] + 4428
23 UIKit                          0x1894f3294 -[UIViewController _performCoordinatedPresentOrDismiss:animated:] + 472
24 UIKit                          0x18927a0c0 -[UIViewController presentViewController:animated:completion:] + 184
25 PrintOSMobile                  0x1000a2894 +[Navigator presentPhoneNumberViewControllerOnAViewController:andDelegate:] (Navigator.m:625)
26 PrintOSMobile                  0x1000b3cd8 -[SetPhoneNumberPopupBuilder presentDialog:withCompletionBlock:] (SetPhoneNumberPopupBuilder.m:68)
27 PrintOSMobile                  0x10006d42c __47-[PopupsManager shouldShowSetPhoneNumberPopup:]_block_invoke (PopupsManager.m:297)
28 PrintOSMobileLibCore           0x1012e45a4 -[ResponseSerializer executeBlock:withResult:] + 48
29 PrintOSMobileLibCore           0x1012e4190 __60-[ResponseSerializer parseJSON:resultClass:success:failure:]_block_invoke + 84
30 libdispatch.dylib              0x1999017b0 _dispatch_call_block_and_release + 24
31 libdispatch.dylib              0x199901770 _dispatch_client_callout + 16
32 libdispatch.dylib              0x199906e20 _dispatch_main_queue_callback_4CF + 1844
33 CoreFoundation                 0x183be4258 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
34 CoreFoundation                 0x183be20c0 __CFRunLoopRun + 1628
35 CoreFoundation                 0x183b10dc0 CFRunLoopRunSpecific + 384
36 GraphicsServices               0x18efac088 GSEventRunModal + 180
37 UIKit                          0x1891eaf60 UIApplicationMain + 204
38 PrintOSMobile                  0x10013c12c main (main.m:14)
39 libdyld.dylib                  0x1999328b8 start + 4

**Comment by grifas** [comment]
Hi @osama-taha thanks to report this crash.

Can you show me how your code ? It will help me to understand the issue

**Comment by grifas** [comment]
I close this issue because no response from @osama-taha
