### ISSUE TITLE
is it possible to add a search box to filter the picker's list?

### ISSUE THREAD

**Issue by razmaimon** [chronotruck/CTKFlagPhoneNumber#9]

**Comment by grifas** [comment]
Hello @razmaimon
I think it's possible but I need to investigate ;)

I keep you in touch.

**Comment by grifas** [comment]
@razmaimon You can try it on the branch [add-search](https://github.com/chronotruck/CTKFlagPhoneNumber/tree/add-search) 

Tell me what do you think about it.

**Comment by osama-taha** [comment]
it works fine, can you please merge your code with the master branch and create a new pod version with this feature?

**Comment by grifas** [comment]
It's merged and the pod `0.3.0` version is available !

**Comment by AsimmParvezz** [comment]
Hi,

The pod 0.3.0 is not available currently

**Comment by grifas** [comment]
@AsimmParvezz Please do a `pod update` to get the latest version

**Comment by AsimmParvezz** [comment]
I get the following error:
[!] Failed to connect to GitHub to update the CocoaPods/Specs specs repo - Please check if you are offline, or that GitHub is down
